Fixed waypoint bug (Incorrect parsing)
StarLoco/StarLoco-Game pull request #14
Opened 2023-03-26 20:50 UTC by Sukiiu

Fix des zapp, quelqu'un sur discord avait ce pb : https://gyazo.com/f749cebd13c4131854815495cff04dcd

2023-03-26 21:12 UTC, Diabu requested changes

2023-03-26 21:12 UTC, Diabu commented on src/org/starloco/locos/client/Player.java
> +    public void useZaap(Integer id) {
Evitons de boxer l'`int` en `Integer` ici. On ne veut pas autoriser la valeur `null`.

2023-03-27 06:09 UTC, Sukiiu commented
Le parsing doit éviter la valeur `null`, loco a effectué le changement pour le zaap sur sa branche, je ferme la PR

2023-03-27 16:41 UTC, StarLoco approved these changes
Good to push

2023-03-27 16:42 UTC, merged